version: "3.3"

services:
  socket-server-example:
    image: socket-server
    build:
      context: ./socket-server-example
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    ports:
      - "3333:3333"
    networks:
      - app-network

  socket-chat-example:
    image: socket-chat
    build:
      context: ./socket-chat-example
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge